name = "SpikingNNFunctions"
uuid = "ac97e89c-ede4-4801-915b-eb83a6cbfe69"
authors = ["Kyle Daruwalla"]
version = "0.2.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CUDA = "1, 2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
